// @generated by scripts/generate-crowdrelay-fan-contract.py; do not hand-edit.
// @crowdrelay-openapi-sha256 251b5fed60d37ec9eac0557accc064ef8f75d26ed39df2950c3fa6bb731e97a2
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum FanRecommendedAction {
    ContinueSynesthesia,
    OpenWallet,
    OpenLiveEvent,
    SharePostShowFeedback,
    GetTicket,
    FollowNextEvent,
    ExploreSignal,
    #[default]
    #[serde(other)]
    Unknown,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FanRecommendedActionDetail {
    pub kind: FanRecommendedAction,
    pub priority: u8,
    pub target: String,
    pub expires_at: Option<String>,
    pub reason: String,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FanHomeData {
    pub schema_version: u32,
    pub generated_at: String,
    pub profile: FanHomeProfile,
    pub next_event: Option<FanHomeEvent>,
    pub synesthesia: FanHomeSynesthesia,
    pub referral: FanHomeReferral,
    pub counts: FanHomeCounts,
    pub recommended_action: FanRecommendedAction,
    #[serde(default)]
    pub recommended: Option<FanRecommendedActionDetail>,
    #[serde(default)]
    pub stale: bool,
}

impl FanHomeData {
    pub const SCHEMA_VERSION: u32 = 1;

    pub fn has_supported_schema(&self) -> bool {
        self.schema_version == Self::SCHEMA_VERSION
    }
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FanHomeProfile {
    pub display_name: Option<String>,
    pub locale: Option<String>,
    pub primary_city: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct FanHomeEvent {
    pub slug: String,
    pub title: String,
    pub venue: Option<String>,
    pub city: Option<String>,
    pub starts_at: String,
    pub doors_at: Option<String>,
    pub ends_at: Option<String>,
    pub phase: String,
    pub ticket_url: Option<String>,
    pub interested: bool,
    pub has_pass: bool,
    pub has_paid_ticket: bool,
    pub ticket_sale_active: bool,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FanHomeSynesthesia {
    pub started: bool,
    pub completed: bool,
    pub rooms_completed: i16,
    pub client_total_elapsed_ms: Option<i64>,
    pub best_elapsed_ms: Option<i64>,
    pub completed_runs: i64,
    pub leaderboard_published: bool,
    pub leaderboard_rank: Option<i64>,
    pub linked_at: Option<String>,
    pub reward_entered: bool,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FanHomeReferral {
    pub qualified: i64,
    pub pending: i64,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize)]
pub struct FanHomeCounts {
    pub event_interests: i64,
    pub active_passes: i64,
    pub paid_orders: i64,
    pub area_claims: i64,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase")]
pub struct FanPushPreferences {
    pub shows: bool,
    pub releases: bool,
    pub community: bool,
    pub merch: bool,
    pub quiet_hours_enabled: bool,
    pub quiet_start: String,
    pub quiet_end: String,
    pub quiet_timezone: String,
}

impl Default for FanPushPreferences {
    fn default() -> Self {
        Self {
            shows: true,
            releases: true,
            community: true,
            merch: true,
            quiet_hours_enabled: false,
            quiet_start: "22:00".to_owned(),
            quiet_end: "08:00".to_owned(),
            quiet_timezone: "Europe/Warsaw".to_owned(),
        }
    }
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
#[serde(rename_all = "camelCase", deny_unknown_fields)]
pub struct FanPushPreferencesUpdate {
    pub shows: bool,
    pub releases: bool,
    pub community: bool,
    pub merch: bool,
    pub quiet_hours_enabled: bool,
    pub quiet_start: String,
    pub quiet_end: String,
}
