#!/usr/bin/env python3
"""Keep the Web/WASM and native Tauri Fan Home DTOs on one shared definition.

The two sides used to declare these structs separately and the contract was held
by comparing them field-for-field. They now share a single generated definition
in virya-signal-contracts, so drift is prevented structurally instead. What has
to be guarded is that neither side quietly reintroduces a local copy, and that
the generated file stays traceable to the CrowdRelay OpenAPI it was cut from.
"""

from __future__ import annotations

import hashlib
import re
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WEB_MODELS = ROOT / "src" / "models.rs"
NATIVE_MODELS = ROOT / "src-tauri" / "src" / "models" / "session_fan.rs"
CONTRACT = ROOT / "crates" / "virya-signal-contracts" / "src" / "fan_wire.generated.rs"

STRUCTS = (
    "FanHomeData",
    "FanHomeProfile",
    "FanHomeEvent",
    "FanHomeSynesthesia",
    "FanHomeReferral",
    "FanHomeCounts",
)


def struct_fields(source: str, name: str) -> tuple[str, ...]:
    match = re.search(
        rf"pub\s+struct\s+{re.escape(name)}\s*\{{(?P<body>.*?)\}}",
        source,
        re.MULTILINE | re.DOTALL,
    )
    if match is None:
        raise AssertionError(f"missing public struct {name}")
    return tuple(
        re.findall(r"\bpub\s+([A-Za-z_][A-Za-z0-9_]*)\s*:", match.group("body"))
    )


class FanHomeContractParityTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls) -> None:
        cls.web = WEB_MODELS.read_text()
        cls.native = NATIVE_MODELS.read_text()
        cls.contract = CONTRACT.read_text()

    def test_every_fan_home_dto_is_defined_once_in_the_shared_contract(self) -> None:
        for name in STRUCTS:
            with self.subTest(struct=name):
                self.assertTrue(
                    struct_fields(self.contract, name),
                    f"{name} must be defined in the shared contract",
                )

    def test_neither_side_redeclares_a_local_copy(self) -> None:
        for label, source in (("wasm", self.web), ("native", self.native)):
            for name in STRUCTS:
                with self.subTest(side=label, struct=name):
                    self.assertNotRegex(
                        source,
                        rf"pub\s+struct\s+{name}\b",
                        f"{label} redeclares {name}; it must come from "
                        "virya_signal_contracts::fan so the two sides cannot drift",
                    )

    def test_both_sides_source_the_dtos_from_the_shared_contract(self) -> None:
        for label, source in (("wasm", self.web), ("native", self.native)):
            with self.subTest(side=label):
                self.assertIn("virya_signal_contracts::fan", source)

    def test_profile_locale_is_part_of_the_contract(self) -> None:
        self.assertIn("locale", struct_fields(self.contract, "FanHomeProfile"))

    def test_generated_contract_records_its_exact_crowdrelay_source(self) -> None:
        self.assertIn("@generated by scripts/generate-crowdrelay-fan-contract.py", self.contract)
        marker = re.search(r"@crowdrelay-openapi-sha256 ([0-9a-f]{64})", self.contract)
        self.assertIsNotNone(marker)
        openapi = ROOT.parent / "crowdrelay" / "openapi" / "openapi.yaml"
        self.assertTrue(openapi.is_file(), "parity check requires the sibling CrowdRelay checkout")
        self.assertEqual(marker.group(1), hashlib.sha256(openapi.read_bytes()).hexdigest())

    def test_generator_pins_field_types_nullability_and_closed_schemas(self) -> None:
        generator = (ROOT / "scripts/generate-crowdrelay-fan-contract.py").read_text()
        for marker in (
            "EXPECTED_INLINE_PROPERTIES",
            "additionalProperties: false",
            "nullable reference contract drifted",
            "quiet_timezone type/bounds drifted",
            "FanRecommendedAction enum drifted",
        ):
            self.assertIn(marker, generator)


if __name__ == "__main__":
    unittest.main()
