name: Security Audit

on:
  workflow_dispatch:
  schedule:
    - cron: "17 5 * * 1"

permissions:
  contents: read

concurrency:
  group: security-audit
  cancel-in-progress: true

jobs:
  dependencies:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
      - uses: taiki-e/install-action@7f4eb899022d8fe70b20c4f3de697aa85c309026 # v2
        with:
          tool: cargo-audit
      - name: Audit Cargo.lock
        run: cargo audit --file Cargo.lock
